DROP DATABASE IF EXISTS EMPRESA_BD;
CREATE DATABASE EMPRESA_BD;

USE EMPRESA_BD;

CREATE TABLE Empresa (
	id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    numeroNit VARCHAR(8) NOT NULL,
    fechaFundacion DATE NULL,
    direccion VARCHAR(150) NOT NULL
    
);